CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255),
    password    VARCHAR(255),
    created_at  TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6)
);

CREATE TABLE follows (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id   BIGINT NOT NULL,
    followee_id   BIGINT NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    modified_at   TIMESTAMP(6) NOT NULL,
    deleted_at    TIMESTAMP(6)
);

CREATE INDEX idx_follows_follower_followee_active ON follows(follower_id, followee_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_follows_followee_active ON follows(followee_id) WHERE deleted_at IS NULL;

CREATE TABLE follow_counts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL UNIQUE,
    followers_count BIGINT NOT NULL,
    followees_count BIGINT NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    modified_at     TIMESTAMP(6) NOT NULL,
    deleted_at      TIMESTAMP(6)
);

CREATE INDEX idx_follow_counts_user_active ON follow_counts(user_id) WHERE deleted_at IS NULL;

CREATE TABLE posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(1000) NOT NULL,
    user_id     BIGINT NOT NULL,
    parent_id   BIGINT,
    quote_id    BIGINT,
    created_at  TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6)
);

CREATE INDEX idx_posts_created_at_active ON posts(created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_parent_created_at_active ON posts(parent_id, created_at ASC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_user_post_created_at_active ON posts(user_id, created_at DESC) WHERE deleted_at IS NULL AND parent_id IS NULL;
CREATE INDEX idx_posts_user_reply_created_at_active ON posts(user_id, created_at DESC) WHERE deleted_at IS NULL AND parent_id IS NOT NULL;
